server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,file:E:/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB